export const CONSTANTS = {
    home: 'HOME',
    showTitle: 'POPULAR SHOWS',
    episodeTitle: 'EPISODE DETAILS',
    episodeMessage: 'No Episodes are released yet',
    nameUnknown: 'Name Unknown',
    unknown: 'Unknown',
    aired: 'Aired',
    genre: 'Genres',
    language: 'Language',
    rating: 'Rating:',
    noRating: 'Rating: NA',
    episodeNumber: 'EPISODE',
    noNumber: 'NA',
    searchTitle: 'SEARCH SHOWS',
    searchMessage: `We couldn't find anything matching. Try searching for another show.`,
    back: 'Back',
    officialSite: 'Go to the official site',
    seasonTitle: 'Seasons',
    castTitle: 'Cast & Crew',
    seasonNumber: 'Season',
    pageNotFoundMessage1: 'Lost Your Way ?',
    pageNotFoundMessage2: `Sorry, we can't find that page.`,
    pageNotFoundMessage3: `You'll find lots to explore on the home page.`,
    backToHome: 'Back To Home',
    showMessage: 'There Are No Shows Available.',
    copyright: '© 2020 Copyright:',
    tvMazeUrl: 'TVMaze.com'
};
